services:
  backend:
    build: ./snapshot-inteligente-backend
    container_name: snapshot-backend
    network_mode: host
    environment:
      BITCOIN_RPC_HOST: 172.17.0.1
      BITCOIN_RPC_PORT: 18443
      BITCOIN_RPC_USER: teste
      BITCOIN_RPC_PASSWORD: teste
      ZMQ_HOST: 172.17.0.1
      ZMQ_PORT: 28332

  frontend:
    image: bitcoincoders-frontend:latest
    container_name: snapshot-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend